### ISSUE TITLE
Feature request: link to code

### ISSUE THREAD

**Issue by Akuli** [hauntsaninja/mypy_primer#10]
Would be nice if I could click lines of `mypy_primer` output in typeshed CI to jump to the code being checked

**Comment by Akuli** [comment]
Actually, I think I can do this myself too, by parsing the output in typeshed CI. Would it be preferable to do that or have mypy_primer output markdown?

**Comment by JelleZijlstra** [comment]
See also #3.

**Comment by Akuli** [comment]
Nevermind, closing as duplicate of #3
