### ISSUE TITLE
Remove the performance regression comments

### ISSUE THREAD

**Issue by JelleZijlstra** [hauntsaninja/mypy_primer#108]
We've had mypy-primer comment about type checking becoming faster or slower for a while now and in my experience, it frequently triggers incorrectly (most recently: https://github.com/python/mypy/pull/16488#issuecomment-1810466683) and never tells us something useful. I think we should remove these comments in the spirit of keeping mypy-primer's output actionable.

**Comment by srittau** [comment]
We could also define a threshold when to show this output. For example, if it got 1.5x slower or 1.5x faster to highlight potential problems. But in general I agree.

**Comment by JelleZijlstra** [comment]
There is already a threshold (1.05x): https://github.com/hauntsaninja/mypy_primer/blob/f02e889c8313b87df09578c7a3ce8af74a26136c/mypy_primer/model.py#L354. Possibly we could raise it, though I think I recall seeing spurious 2x performance changes too.

**Comment by hauntsaninja** [comment]
Removed in 49f8628

**Comment by hauntsaninja** [comment]
I'm bringing this back with a significantly higher threshold (e.g. would have been nice to catch https://github.com/microsoft/pyright/issues/9118 ).

I went through historical mypy and typeshed issues to pick the new threshold. Jelle is right that there are some crazy spurious differences (like https://github.com/python/typeshed/pull/10370#issuecomment-1611150901 ), but these are fairly uncomment
