### ISSUE TITLE
different running times with 2 shards

### ISSUE THREAD

**Issue by Akuli** [hauntsaninja/mypy_primer#11]
In typeshed CI, shard 0 seems to be consistently slower than shard 1. Consider https://github.com/python/typeshed/runs/2704740809 for example, shard 0 runs in 29min while shard 1 runs in 19min. Ideally both would run in 25min, making the CI slightly faster overall.

Maybe this is because the projects in the beginning of the project list are somehow slower?

**Comment by hauntsaninja** [comment]
I think there are a couple projects that are really slow (I think maybe scipy takes like 5m to type check? And I think that's with mypyc). Here's the logic for sharding, and as you can see it's not the cleverest thing ever written: https://github.com/hauntsaninja/mypy_primer/blob/fec2f868122af75dfce47bb333768a1923b103fb/mypy_primer.py#L538

Possible action items we could take to speed up typeshed CI:
1) Nothing — just wait till mypy releases a mypyc compiled mypy and things become much faster. It's claimed that mypy will make a release in the next week or two, but mypy has missed release targets many times before.
2) Use a prerelease mypyc compiled mypy from https://github.com/mypyc/mypy_mypyc-wheels
3) Increase the number of shards
4) Remove from mypy primer any projects we deem too slow
5) Change mypy primer sharding to somehow take into account project runtimes

Thoughts?

**Comment by srittau** [comment]
I would recommend waiting for the next mypy release first. After that, possibly removing very expensive projects would be a next thing to look at.

**Comment by srittau** [comment]
After pinning mypy to 0.901, primer now runs in 6 minutes in typeshed.
