### ISSUE TITLE
Unexpected result when downstream fork is behind master

### ISSUE THREAD

**Issue by tushar-deepsource** [hauntsaninja/mypy_primer#21]
So I recently found out that if your downstream fork of mypy is behind upstream's master, the mypy_primer report in GitHub CI is going to show unexpected results.

This is because even though the "files changed" section in GitHub's PR shows a small difference between the two branches, mypy_primer sees very different code, causing unrelated diffs.

Is it possible to add an option in mypy_primer to merge upstream's master into the code, to avoid this?

**Comment by hauntsaninja** [comment]
Thanks for the report! I opted to just go with using the merge base in https://github.com/python/mypy/pull/11627 (easy to implement and understand, always give PR author feedback, complicated relationships between PRs not captured by unit tests are very rare for mypy)

**Comment by JelleZijlstra** [comment]
I merged the mypy PR.
