### ISSUE TITLE
mypy-primer seems to be failing in mypy's Github Actions

### ISSUE THREAD

**Issue by A5rocks** [hauntsaninja/mypy_primer#25]
mypy-primer's github action seems to be failing: [here on @sobolevn's PR](https://github.com/python/mypy/runs/4637719122?check_suite_focus=true) and [here on my own PR](https://github.com/python/mypy/runs/4638785207?check_suite_focus=true).

Perhaps a good first step would be having mypy-primer log output of the git clone function? It looks like that information already exists: https://github.com/hauntsaninja/mypy_primer/blob/313288c40beb24e464a0ec123480698110ad4ae2/mypy_primer.py#L109

To me, it looks like it's trying to clone a repository twice which... what? Nothing changed, why is that happening? Looks like this is the piece of code that's being weird:

https://github.com/hauntsaninja/mypy_primer/blob/313288c40beb24e464a0ec123480698110ad4ae2/mypy_primer.py#L163-L164

**Comment by hauntsaninja** [comment]
Thanks, mypy_primer seems to be working fine on recent PRs, so I'm inclined to think something spurious on Github's side was causing clones to fail.
Having prettier error handling that logs output would be useful.

**Comment by A5rocks** [comment]
Yep definitely seems to have been some GitHub flakiness, I'll close this then.
