### ISSUE TITLE
Compare run time to flag performance regressions

### ISSUE THREAD

**Issue by huguesb** [hauntsaninja/mypy_primer#30]
It would be useful for mypy_primer to keep track of run times, compute a percent change, and report it when above a configurable threshold.

This would allow flagging performance regressions caused by mypy PRs, and could also validate the real-world impact of any optimizations.

Caveat: it might require more than 1 run of each branch to get reliable timings on CI

**Comment by hauntsaninja** [comment]
That's a great idea. Like you say, will depend on how stable timings are in CI.

**Comment by hauntsaninja** [comment]
I've added this to the mypy_primer output, we'll see how reliable the timings are
