### ISSUE TITLE
add cki-lib?

### ISSUE THREAD

**Issue by Akuli** [hauntsaninja/mypy_primer#32]
https://gitlab.com/cki-project/cki-lib has some code that uses `requests`, apparently beyond the very high-level api: https://github.com/python/typeshed/issues/7776

**Comment by inakimalerba** [comment]
Hello ! 

Thanks a lot for considering enhancing `cki-lib` with some typing :) We're flattered !

We're trying to include typing annotations directly into the code of all the projects in the [cki-project](gitlab.com/cki-project/) namespace. It's a bit tricky as some of those pieces run in pretty old python versions, but we're getting there.

We welcome all contributions into our projects, there are some development guidelines [around here](https://cki-project.org/docs/hacking/contributing/development-guidelines/) in case that's useful.

**Comment by Akuli** [comment]
> Thanks a lot for considering enhancing cki-lib with some typing :) We're flattered !

Sorry to disappoint, but that's not exactly what this issue is about :)

`mypy_primer` is a tool that runs mypy with two different copies of typeshed and compares the results. This is useful in typeshed pull requests: if someone makes a PR that breaks your `requests.hooks` code, we want to know that before we even review the PR, not a few days/weeks after the PR is merged and you make an issue to typeshed. This is what adding cki-lib to mypy_primer is all about.

For a project to be useful in mypy_primer, it just has to be a relatively big project that uses type annotations, and preferably uses some library or part of a library that other projects in mypy_primer don't. For example, mypy_primer includes one of my personal projects because no other project in mypy_primer contains tkinter code (as far as I know).

**Comment by inakimalerba** [comment]
Gotta say that makes a lot more sense now :smile:  

Thanks for the explanation!

**Comment by hauntsaninja** [comment]
Thanks Akuli, added this! inakimalerba, please feel free to let us know if you run into issues as you add more types to your code! :-)
