### ISSUE TITLE
Print truncated in number of lines, not chars?

### ISSUE THREAD

**Issue by ethanhs** [hauntsaninja/mypy_primer#36]
Looking at https://github.com/python/mypy/pull/12901 it occurs to me since our errors are more line-oriented, it may make more sense to print the number of lines truncated instead of number of characters.

For example, in that PR, it tells me nothing that there are 3M truncated characters (well, other than there are a *lot* more errors) but number of lines would give a better approximate number of errors reported.

**Comment by hauntsaninja** [comment]
Good point, fixed in https://github.com/python/mypy/pull/12910 and https://github.com/python/typeshed/pull/7993

**Comment by ethanhs** [comment]
Thanks!
