### ISSUE TITLE
Better balanced shards

### ISSUE THREAD

**Issue by A5rocks** [hauntsaninja/mypy_primer#58]
I would *love* if mypy primer better balanced sharding. On a recent PR to mypy, I noticed that:
 - shard 0 only took 7 minutes
 - shard 1 took 27 minutes
 - shard 2 took 14 minutes
 - shard 3 took 20 minutes
 - shard 4 took 21 minutes

(Note that mypy-primer could take ~10 minutes less if it optimally balanced)

I know that it would be infeasible to construct lists for every single combination, so I propose:

What if every project had a "difficulty" number that was a rough estimate of time mypy takes to type check it? The idea is that you could try to balance these numbers into buckets (just use a greedy approach: from largest difficulty to smallest just always put it in the lowest difficulty bucket).

I'm not sure how we could keep these up to date though. Is there a metric that is simple to take but that correlates with mypy runtime? Number of files? Dependencies? Lines of code? Count of `import typing`?

**Comment by hauntsaninja** [comment]
Yeah, agreed that this would be nice.

The distribution is quite head heavy (cough sympy cough), so I think you could get most of the benefit by just adding a manual score to the longest ones. `mypy_primer --measure-project-runtimes --concurrency 1` should show project runtimes.

An amusing fact: at one point I noticed there was a particularly bad sharding, so my quick fix was: https://github.com/hauntsaninja/mypy_primer/blob/236dab370d45dccd2ac17e67180cd7d3e99248af/mypy_primer.py#L60

A random musing: I've been curious about this but haven't looked at it yet is investigating how the mypyc-compiled mypy to pure-python mypy speed differs across projects

**Comment by wyattscarpenter** [comment]
I'm seeing a lot of mypy_primer diffs lately, and I've noticed a similar situation (the same problem? a new problem?)

For instance, on mypy's 5-sharded workflow:

![Image](https://github.com/user-attachments/assets/421b9869-0619-47ae-8e75-20c2aaab9bcf)

On [basedpyright](https://github.com/DetachHead/basedpyright/pull/1267)'s 8-sharded:

![Image](https://github.com/user-attachments/assets/9e55794e-b486-49e3-bc73-cde7d8f3c915)

**Comment by wyattscarpenter** [comment]
Oh, is the system still based on manually setting costs? I can see how that would get inaccurate.

**Comment by hauntsaninja** [comment]
Yeah, costs are set manually. You can use `--measure-project-runtimes` to make setting them easier.

I think colour science project setup got fixed at some point and this is a really slow project when run with uncompiled mypy. Better balancing could make the slow shard go from 43m to 35m..

In the basedpyright run you link to, homeassistant takes 45m. Better balancing could make the slow shard go from 51m to 45m
