### ISSUE TITLE
The porcupine project is broken with mypy github master

### ISSUE THREAD

**Issue by JukkaL** [hauntsaninja/mypy_primer#6]
The value of `custom_typeshed_dir` is incorrect in `porcupine`, and the latest mypy complains about it:

```
$ cat porcupine/mypy.ini
[mypy]
warn_unused_configs = True
warn_unused_ignores = True
disallow_untyped_defs = True
show_error_codes = True
custom_typeshed_dir = typeshed
```

The directory `typeshed` is actually empty.

Here's the failure:
https://github.com/python/mypy/pull/9984/checks?check_run_id=1779046241

Also the error reporting is not super clear. It would be good to give the name of the project that is failing prominently.

**Comment by hauntsaninja** [comment]
Thanks for reporting! Fixed on master. The error reporting was an issue with mypy_primer trying too hard to validate mypy output. I've removed that since it's not useful.
