### ISSUE TITLE
Ensure mypy_primer uses third party typeshed stubs in typeshed CI

### ISSUE THREAD

**Issue by hauntsaninja** [hauntsaninja/mypy_primer#7]
Following the refactor, this is no longer the case. Just filing this as a reminder to get things working.

**Comment by JukkaL** [comment]
It would be good to have an option to install known third-party type packages generally, or at least in mypy CI. Since we no longer ship third-party package stubs with mypy, not having them limits the precision of type checking and inferred types, possibly quite significantly.

**Comment by hauntsaninja** [comment]
Note that I've since updated most projects to install the type stubs they need from PyPI, so for the purposes of evaluating mypy regressions we're in good shape. But we still can't evaluate typeshed regressions on third party stubs (the core of this issue).
